#!/usr/bin/env python3

import sys
count = len(sys.argv)

i = 0
x = 0

if count == 1:
    while i < 11:
        print(f"Table de {i}: ", end=" ")
        while x < 11:
            print(x * i , end=" ")
            x += 1
        print(" ")
        x = 0
        i += 1
        
else:
    print("none")
      
           


