#!/usr/bin/env python

num = input("Enter a number: ")
if int(num) > 0:
    print("This number is positive.")
elif int(num) < 0:
    print("This number is negative.")
else:
    print("This number is both positive and negative.")
